
export const preset_category_palettes = [
    {
        palette: "General",
        categories: [
            { category: "Work", editable: false, description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, " },
            { category: "Sleep", editable: false , description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, " },
            { category: "Tasks", editable: false , description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, " },
            { category: "Socialising", editable: false , description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, " },
            { category: "Learning", editable: false , description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, " },
            { category: "Making", editable: false , description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, " },
        ]
    },
    {
        palette: "Making",
        categories: [
            { category: "Planning project", editable: false , description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, " },
            { category: "Sourcing materials", editable: false , description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, " },
            { category: "Actually making", editable: false , description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, " },
            { category: "Stuff that stimulates", editable: false , description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, " },
            { category: "No creative value", editable: false , description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, " }
        ]
    },
    {
        palette: "Mood",
        categories: [
            { category: "Neutral", editable: false , description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, " },
            { category: "Anxious", editable: false , description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, " },
            { category: "Sad", editable: false , description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, " },
            { category: "Content", editable: false , description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, " },
            { category: "Stimulated", editable: false , description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, " },
            { category: "Drained", editable: false , description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, " }
        ]
    },
    {
        palette: "Create your own",
        categories: []
    }
];

// export const dummy_categories = ["Work", "Sleep", "Tasks", "Socialising", "Learning", "Making"];
export const dummy_categories = [
    { category:"Work", description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, " },
    { category:"Sleep", description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, " },
    { category:"Tasks", description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, " },
    { category: "Socialising",description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, " },
    { category: "Learning",description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, " },
    { category:  "Making",description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, " },
];

export const dummy_week_data =[
    {
        "categories": [
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "unfilled",
                "6": "unfilled",
                "7": "filled",
                "8": "unfilled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "unfilled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "filled",
                "19": "filled",
                "20": "filled",
                "21": "filled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Work"
            },
            {
                "0": "filled",
                "1": "filled",
                "2": "filled",
                "3": "filled",
                "4": "filled",
                "5": "filled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "unfilled",
                "16": "filled",
                "17": "unfilled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Sleep"
            },
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "unfilled",
                "6": "filled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "unfilled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Tasks"
            },
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "unfilled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "filled",
                "10": "filled",
                "11": "filled",
                "12": "filled",
                "13": "filled",
                "14": "filled",
                "15": "filled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Socialising"
            },
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "unfilled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "filled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "unfilled",
                "16": "unfilled",
                "17": "filled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Learning"
            },
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "unfilled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "unfilled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "filled",
                "23": "filled",
                "category": "Making"
            }
        ],
        "aggregate": {
            "0": "Sleep",
            "1": "Sleep",
            "2": "Sleep",
            "3": "Sleep",
            "4": "Sleep",
            "5": "Sleep",
            "6": "Tasks",
            "7": "Work",
            "8": "Learning",
            "9": "Socialising",
            "10": "Socialising",
            "11": "Socialising",
            "12": "Socialising",
            "13": "Socialising",
            "14": "Socialising",
            "15": "Socialising",
            "16": "Sleep",
            "17": "Learning",
            "18": "Work",
            "19": "Work",
            "20": "Work",
            "21": "Work",
            "22": "Making",
            "23": "Making"
        }
    },
    {
        "categories": [
            {
                "0": "filled",
                "1": "filled",
                "2": "filled",
                "3": "filled",
                "4": "filled",
                "5": "unfilled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "unfilled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Work"
            },
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "unfilled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "filled",
                "12": "filled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "unfilled",
                "16": "filled",
                "17": "filled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "filled",
                "22": "filled",
                "23": "filled",
                "category": "Sleep"
            },
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "filled",
                "6": "filled",
                "7": "filled",
                "8": "filled",
                "9": "filled",
                "10": "unfilled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "unfilled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Tasks"
            },
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "unfilled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "unfilled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "filled",
                "19": "filled",
                "20": "filled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Socialising"
            },
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "unfilled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "unfilled",
                "10": "filled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "filled",
                "14": "filled",
                "15": "filled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Learning"
            },
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "unfilled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "unfilled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Making"
            }
        ],
        "aggregate": {
            "0": "Work",
            "1": "Work",
            "2": "Work",
            "3": "Work",
            "4": "Work",
            "5": "Tasks",
            "6": "Tasks",
            "7": "Tasks",
            "8": "Tasks",
            "9": "Tasks",
            "10": "Learning",
            "11": "Sleep",
            "12": "Sleep",
            "13": "Learning",
            "14": "Learning",
            "15": "Learning",
            "16": "Sleep",
            "17": "Sleep",
            "18": "Socialising",
            "19": "Socialising",
            "20": "Socialising",
            "21": "Sleep",
            "22": "Sleep",
            "23": "Sleep"
        }
    },
    {
        "categories": [
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "unfilled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "unfilled",
                "12": "filled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "unfilled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Work"
            },
            {
                "0": "filled",
                "1": "filled",
                "2": "filled",
                "3": "filled",
                "4": "filled",
                "5": "unfilled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "filled",
                "16": "filled",
                "17": "filled",
                "18": "filled",
                "19": "filled",
                "20": "filled",
                "21": "filled",
                "22": "filled",
                "23": "filled",
                "category": "Sleep"
            },
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "unfilled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "filled",
                "12": "unfilled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "unfilled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Tasks"
            },
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "filled",
                "6": "filled",
                "7": "filled",
                "8": "filled",
                "9": "filled",
                "10": "filled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "unfilled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Socialising"
            },
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "unfilled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "filled",
                "14": "filled",
                "15": "unfilled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Learning"
            },
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "unfilled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "unfilled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Making"
            }
        ],
        "aggregate": {
            "0": "Sleep",
            "1": "Sleep",
            "2": "Sleep",
            "3": "Sleep",
            "4": "Sleep",
            "5": "Socialising",
            "6": "Socialising",
            "7": "Socialising",
            "8": "Socialising",
            "9": "Socialising",
            "10": "Socialising",
            "11": "Tasks",
            "12": "Work",
            "13": "Learning",
            "14": "Learning",
            "15": "Sleep",
            "16": "Sleep",
            "17": "Sleep",
            "18": "Sleep",
            "19": "Sleep",
            "20": "Sleep",
            "21": "Sleep",
            "22": "Sleep",
            "23": "Sleep"
        }
    },
    {
        "categories": [
            {
                "0": "filled",
                "1": "filled",
                "2": "filled",
                "3": "filled",
                "4": "filled",
                "5": "unfilled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "unfilled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "filled",
                "23": "filled",
                "category": "Work"
            },
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "filled",
                "6": "filled",
                "7": "filled",
                "8": "filled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "filled",
                "16": "filled",
                "17": "unfilled",
                "18": "filled",
                "19": "filled",
                "20": "filled",
                "21": "filled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Sleep"
            },
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "unfilled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "unfilled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Tasks"
            },
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "unfilled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "filled",
                "10": "filled",
                "11": "filled",
                "12": "filled",
                "13": "filled",
                "14": "filled",
                "15": "unfilled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Socialising"
            },
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "unfilled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "unfilled",
                "16": "unfilled",
                "17": "filled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Learning"
            },
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "unfilled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "unfilled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Making"
            }
        ],
        "aggregate": {
            "0": "Work",
            "1": "Work",
            "2": "Work",
            "3": "Work",
            "4": "Work",
            "5": "Sleep",
            "6": "Sleep",
            "7": "Sleep",
            "8": "Sleep",
            "9": "Socialising",
            "10": "Socialising",
            "11": "Socialising",
            "12": "Socialising",
            "13": "Socialising",
            "14": "Socialising",
            "15": "Sleep",
            "16": "Sleep",
            "17": "Learning",
            "18": "Sleep",
            "19": "Sleep",
            "20": "Sleep",
            "21": "Sleep",
            "22": "Work",
            "23": "Work"
        }
    },
    {
        "categories": [
            {
                "0": "filled",
                "1": "filled",
                "2": "filled",
                "3": "filled",
                "4": "filled",
                "5": "filled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "unfilled",
                "16": "filled",
                "17": "filled",
                "18": "filled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Work"
            },
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "unfilled",
                "6": "filled",
                "7": "filled",
                "8": "filled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "unfilled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "unfilled",
                "19": "filled",
                "20": "filled",
                "21": "filled",
                "22": "filled",
                "23": "filled",
                "category": "Sleep"
            },
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "unfilled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "filled",
                "10": "unfilled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "unfilled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Tasks"
            },
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "unfilled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "unfilled",
                "10": "filled",
                "11": "filled",
                "12": "filled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "unfilled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Socialising"
            },
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "unfilled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "unfilled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Learning"
            },
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "unfilled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "filled",
                "14": "filled",
                "15": "filled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Making"
            }
        ],
        "aggregate": {
            "0": "Work",
            "1": "Work",
            "2": "Work",
            "3": "Work",
            "4": "Work",
            "5": "Work",
            "6": "Sleep",
            "7": "Sleep",
            "8": "Sleep",
            "9": "Tasks",
            "10": "Socialising",
            "11": "Socialising",
            "12": "Socialising",
            "13": "Making",
            "14": "Making",
            "15": "Making",
            "16": "Work",
            "17": "Work",
            "18": "Work",
            "19": "Sleep",
            "20": "Sleep",
            "21": "Sleep",
            "22": "Sleep",
            "23": "Sleep"
        }
    },
    {
        "categories": [
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "filled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "filled",
                "14": "filled",
                "15": "unfilled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Work"
            },
            {
                "0": "filled",
                "1": "filled",
                "2": "filled",
                "3": "filled",
                "4": "filled",
                "5": "unfilled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "unfilled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "filled",
                "19": "filled",
                "20": "filled",
                "21": "filled",
                "22": "filled",
                "23": "filled",
                "category": "Sleep"
            },
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "unfilled",
                "6": "unfilled",
                "7": "filled",
                "8": "filled",
                "9": "filled",
                "10": "filled",
                "11": "filled",
                "12": "filled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "unfilled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Tasks"
            },
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "unfilled",
                "6": "filled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "unfilled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Socialising"
            },
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "unfilled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "filled",
                "16": "filled",
                "17": "filled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Learning"
            },
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "unfilled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "unfilled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Making"
            }
        ],
        "aggregate": {
            "0": "Sleep",
            "1": "Sleep",
            "2": "Sleep",
            "3": "Sleep",
            "4": "Sleep",
            "5": "Work",
            "6": "Socialising",
            "7": "Tasks",
            "8": "Tasks",
            "9": "Tasks",
            "10": "Tasks",
            "11": "Tasks",
            "12": "Tasks",
            "13": "Work",
            "14": "Work",
            "15": "Learning",
            "16": "Learning",
            "17": "Learning",
            "18": "Sleep",
            "19": "Sleep",
            "20": "Sleep",
            "21": "Sleep",
            "22": "Sleep",
            "23": "Sleep"
        }
    },
    {
        "categories": [
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "unfilled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "unfilled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Work"
            },
            {
                "0": "filled",
                "1": "filled",
                "2": "filled",
                "3": "filled",
                "4": "filled",
                "5": "filled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "unfilled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "filled",
                "19": "filled",
                "20": "filled",
                "21": "filled",
                "22": "filled",
                "23": "filled",
                "category": "Sleep"
            },
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "unfilled",
                "6": "filled",
                "7": "filled",
                "8": "filled",
                "9": "filled",
                "10": "filled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "filled",
                "16": "filled",
                "17": "filled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Tasks"
            },
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "unfilled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "unfilled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Socialising"
            },
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "unfilled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "filled",
                "12": "filled",
                "13": "filled",
                "14": "filled",
                "15": "unfilled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Learning"
            },
            {
                "0": "unfilled",
                "1": "unfilled",
                "2": "unfilled",
                "3": "unfilled",
                "4": "unfilled",
                "5": "unfilled",
                "6": "unfilled",
                "7": "unfilled",
                "8": "unfilled",
                "9": "unfilled",
                "10": "unfilled",
                "11": "unfilled",
                "12": "unfilled",
                "13": "unfilled",
                "14": "unfilled",
                "15": "unfilled",
                "16": "unfilled",
                "17": "unfilled",
                "18": "unfilled",
                "19": "unfilled",
                "20": "unfilled",
                "21": "unfilled",
                "22": "unfilled",
                "23": "unfilled",
                "category": "Making"
            }
        ],
        "aggregate": {
            "0": "Sleep",
            "1": "Sleep",
            "2": "Sleep",
            "3": "Sleep",
            "4": "Sleep",
            "5": "Sleep",
            "6": "Tasks",
            "7": "Tasks",
            "8": "Tasks",
            "9": "Tasks",
            "10": "Tasks",
            "11": "Learning",
            "12": "Learning",
            "13": "Learning",
            "14": "Learning",
            "15": "Tasks",
            "16": "Tasks",
            "17": "Tasks",
            "18": "Sleep",
            "19": "Sleep",
            "20": "Sleep",
            "21": "Sleep",
            "22": "Sleep",
            "23": "Sleep"
        }
    }
];